name: build for all platforms

on:
    push:
        branches: [main, master]
    workflow_dispatch:

jobs:
    # build4iOS:
    #     runs-on: macos-latest
    #     steps:
    #         - name: Clone repository
    #           uses: actions/checkout@v4
    #         - name: Set up Flutter
    #           uses: subosito/flutter-action@v2
    #           with:
    #               channel: beta
    #         - run: flutter pub get
    #         - run: flutter test
    #         - run: flutter build ios --release --no-codesign

    build4Windows:
        runs-on: windows-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: beta
            - run: flutter build windows

            - name: Upload Build Result
              uses: actions/upload-artifact@v3
              with:
                name: randomfortune-exe
                path: build/windows/x64/runner/Release/randomfortune.exe

    # build4Linux:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Clone repository
    #           uses: actions/checkout@v4
    #         - name: Set up Flutter
    #           uses: subosito/flutter-action@v2
    #           with:
    #               channel: beta
    #         - run: |
    #               sudo apt-get update -y
    #               sudo apt-get install -y ninja-build libgtk-3-dev
    #         - run: flutter build linux

    build4macOS:
        runs-on: macos-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: beta
            - run: flutter build macos

            - name: Upload Build Result
              uses: actions/upload-artifact@v3
              with:
                name: randomfortune-app
                path: build/macos/Build/Products/Release/randomfortune.app
